### ISSUE TITLE
Building a Hello World app for the Apple Watch

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/learn-apple-watch-development#11]
This is me thinking in terms of the absolute beginning of what one should be able to achieve before proceeding onto more difficult aspects of developing for watchOS. 

After having spent a few hours setting up something very basic on iPhone here #10. I think I am ready to build the `Hello World` app for the apple watch(AW). 

**Task**
- [ ] Display `Hello World!` on the AW.
- [ ] Document the process of creating the AW app

**Estimated Time** for completion is 1 Hour.

**Comment by sohilpandya** [comment]
1. Create a new App 
    - select watchOS as the platform

**Comment by sohilpandya** [comment]
### Create a Counter from the basics that were taught in #10 

- [ ] Create a button and link it to the controller
- [ ] Create a label and link it to the controller
- [ ] On click of the button increment the number

<img width="1680" alt="screen shot 2016-11-01 at 18 16 55" src="https://cloud.githubusercontent.com/assets/2305591/19901608/8d3cc682-a05f-11e6-8629-6106f1adeddc.png">
