### ISSUE TITLE
Investigate Heart Rate and Accelerometer APIs on Apple Watch for Automatic Activity Tracking

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-apple-watch-development#35]
Hi @sohilpandya,
Hope your _morning_ is going _well_!
Hope your **neck** is feeling **_much_ better** and you're [`$.ready()`](https://youtu.be/zwcpM0mXoPg?t=21s) to receive your next [_mission_](https://youtu.be/K0KzvD-0rx0)! 😉 

You've done a _great job so far_ of building the (_Alpha_) **Time App**
and it's going to be _even_ better once our API is Live! 

## _Ideal_ "User Story"

> As a **person _using_** the **dwyl app**
> I want to **track** my **activities _automatically_**
> So that I **don't have to _think_** about (_**remember** to_) **_manually_ start** a **timer** on my device/app

As you recall from our initial discussion last November on doing Apple Watch Development,
the _reason_ for having an Apple Watch (_Native_) App is not _just_ to be able to "_Tap to start a timer_".
(_or as a "**Vanity Project**" to **say** that **we know** how to write **swift** @dwyl ..._)
 The _beauty_ "_Wearable_" is that has _sensors_ that can be used to `trigger` events! e.g:
+ Sleeping
+ Exercising
+ Meditating
+ Working on something that requires concentration (_what is the heart rate pattern for this?_) 💭 

While you are "_waiting_" for the API to be `ready` ...
(_promise I'll be back working on API as soon as my current client DevOps work is `done`!_)
I thought it would be a _good_ time to start investigating _other_ Apple Watch (WatchKit) APIs!

I know Heart Rate Monitoring _might_ appear to be a "_side track_" from the "Task Timing" project,
But _actually_ tapping into the Heart Rate Monitor gets us to our _Goal_  of **_Automatic_ Activity Tracking** (_**without** requiring the user to **manually start** the **timer**_)!

## Todo / Tasks

+ [ ] Investigate how sleep trackers work https://github.com/dwyl/sleep/issues/8
+ [ ] Investigate using the Apple HealthKit API: https://developer.apple.com/healthkit
+ How can we use Heart Rate and Accelerometer API to **_automatically_ track activity**?
  + how complicated is it to sample the heart rate?
    + [ ] Determine what frequency we should sample heart rate.
    + [ ] Calculate person's resting heart rate by sampling at several times during the day
+ [ ] what is the typical frequency required to effectively track heart rate during various activities:
  + [ ] Concentrated (deep) work
  + [ ] physical activity
  + [ ] Resting/Sleeping
+ [ ] Can we _export_ this **data** to our own API/Backend (_preferably stream in real-time but if not via REST API?_)

Watch this video: https://youtu.be/CfbvT_vCcwc it's pretty much the "Killer App" for Apple Watch (_excuse the terrible pun! but it's a **compelling reason** to own and give one to a loved one!_)

As usual, make sure you _ask_ any relevant questions on GitHub first, 
then link back to GH from StackOverflow so we `continue` to keep our knowledge here.
(_which appears to be pretty active for http://stackoverflow.com/questions/tagged/apple-watch ..._)

Relates to: https://github.com/dwyl/sleep/issues/7

**Comment by sohilpandya** [comment]
@nelsonic ❤️ this and I'll be looking into this very soon, really excited to look into this. 👍

**Comment by sohilpandya** [comment]
I'd like to spike this whole user story that you've created above, Giving myself a full day to see how far I can get with all the items you've mentioned above.

**Comment by sohilpandya** [comment]
Investigated Sleep Tracking on this issue https://github.com/dwyl/sleep/issues/8

## Healthkit

All health kit data is collected using either the iPhone or Watch, the data collected is stored in an encrypted database called **HealthKit store** Which can be accessed using [`HKHealthSrore`](https://developer.apple.com/documentation/healthkit/hkhealthstore) class. 

Both iPhone and the Watch have its own HealthKit store and the data is synced between the two devices. but, old data is removed from the Watch to save space. 

Health is a sensitive topic hence Apple provide fine grain control to the user in terms of what information is shareable to the third party app. We would have to specify exactly what data we need from health kit. (heart rate, steps, birthdate, weight, height, sex etc.)

![screen shot 2017-07-11 at 12 32 42](https://user-images.githubusercontent.com/2305591/28066491-14dcb5e8-6635-11e7-9e74-62076c81ca73.png)

**Apple** states that any app that uses health kit must be primarily designed to provide heath or fitness services and provide a privacy policy.

**Comment by sohilpandya** [comment]
Nelson asked a question regarding **how the data is stored on the iPhone in the first place and how 3rd party apps can access it.** 

- iPhone/Watch start recording data automatically, this is stored in Healthkit Store which is an encrypted database.
- This is the information that is present in the Health app and Apple use it to display information to the user. 
![img_fa97202275fc-1](https://user-images.githubusercontent.com/2305591/28079423-45faec00-6660-11e7-81fd-600b82e7eede.jpeg)
- If a 3rd party app wants to use the data, then they need to ask for permission from the user to access the data. Even then the app can only ask for data when it is running and in the foreground, access to Healthkit data is not possible in the background (security reasons)
- I'll show a brief example of how to access this data in a tutorial.

**Comment by sohilpandya** [comment]
**1.5 Days spent on this issue in total. (estimated only 1 day)**

**Comment by nelsonic** [comment]
@sohilpandya did you record a video summary (_or our standup where the functionality was discussed_)  ?

**Comment by sohilpandya** [comment]
I have the hangout that we recorded on the 11th July, where we walked through the issue as well as the demo app which showed user the total number of steps. https://github.com/dwyl/learn-apple-watch-development/issues/43

**Comment by nelsonic** [comment]
@sohilpandya sweet! have you uploaded it somewhere?

**Comment by sohilpandya** [comment]
@nelsonic I've got quite a few of them stored away on the laptop, not anywhere online, I'll get them transferred to our Gdrive folder at some point today. :)

**Comment by sohilpandya** [comment]
Here is the link https://drive.google.com/drive/u/1/folders/0BzAgO1bmVDtpSU9KZTZEaTdOS00

11th July is on the drive now.

**Comment by nelsonic** [comment]
@sohilpandya thanks! 🎉
