### ISSUE TITLE
Screencast for UI Automation testing 

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/learn-apple-watch-development#40]
As suggested by @nelsonic and doing some research on YT, there doesn't seem to a UI Automation Tutorial out there, so might be worth getting one up just to see what the response is like.

**Todo list for the tutorial**
- [ ] walk through the current state of the app
- [ ] explain a scenario you would like to test
- [ ] record that scenario
- [ ] write test for that scenario
- [ ] run test for the scenario and see it in action. 
- [ ] talk about caveats (swipe feature, the recording interrupted by error message etc.

**Comment by sohilpandya** [comment]
- [ ] Start the video with a little hello
  - talk about the subject that will be discussed in the screencast
  - What is UI automated testing, it's where tests drive the application through the user interface and see if the result is as expected with the user interface functioning correctly

**Comment by sohilpandya** [comment]
Here is the outcome of this screencast. https://drive.google.com/a/dwyl.com/file/d/0BzAgO1bmVDtpdUgzMjNGQ1YzMk0/view?usp=sharing

Can you please watch it and let me know what you make of it. I'd like to put it up on our YouTube channel but need an intro segment. 👍

**Comment by nelsonic** [comment]
"very short tutorial" 12:42 😉 
Much of the text is illegible on my tiny screen:
![image](https://user-images.githubusercontent.com/194400/27562392-43a1b5ee-5ac4-11e7-97a3-c89bd8d49df8.png)
But _bare-in-mind_ that my screen has more pixels than most phones (_where many people consume content_) ... and if you check the latest stats, the "crapy" ***1366 x 768*** resolution is still _by far_ the most popular on Laptop & Tablet:
http://gs.statcounter.com/#resolution-ww-monthly-201704-201705
![image](https://user-images.githubusercontent.com/194400/27562521-c4408784-5ac4-11e7-841c-2c7963522a84.png)

As for the _content_ it's _really_ good. ✅ 
But, as discussed a "demo" of the test running would be a great intro ...
I would split this tutorial into similar sections to @Cleop's table in: https://github.com/dwyl/tachyons-bootstrap/issues/9#issuecomment-311106984

Let's be clear, the video is **_already_ good** and you `should` _publish_ it 
and see if you get some `public` feedback from the people who attended the Swift meetup.

But if you want to _improve_ it, you could _cut_ it down by a few minutes and improve the organisation.
1. This is automated UI testing in action (15 seconds of demo)
2. We do automated UI testing because it improves the reliability of our apps which means we can ship features faster. (_10 seconds show good reviews for app like CityMapper and bad reviews for app that crashes_)
3. Here's the "hello world" of UI testing from scratch (_3-5 mins_)
4. Here's how you add UI testing to an _existing_ app (_show dwyl's app for 3-5mins_)
5. Conclusion (1 min)
